application: my-mod-ex
module: my-dev-service
version: 2
runtime: go
api_version: go1

handlers:
- url: /.well-known
  static_dir: static/.well-known

- url: /static
  static_dir: static
  secure: always
  http_headers:
    Access-Control-Allow-Origin: https://*.appspot.com

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*~)$
- ^(.gitignore)$
- ^(.git)$
